export const MOVE_SELECTED = "MOVE_SELECTED";
export const HOVER_POSITION ="HOVER_POSITION";
export const PLAYER_PASS ="PLAYER_PASS";
export const CONNECTION_MADE ="CONNECTION_MADE";
export const UPDATE_NAME = "UPDATE_NAME";
export const START_NEW_GAME = "START_NEW_GAME";
export const LEAVE_GAME  = "LEAVE_GAME";
export const SAVE_PLAYER_NAME  = "SAVE_PLAYER_NAME";
export const NEW_GAME_CREATED = "NEW_GAME_CREATED";
export const GAME_STARTED = "GAME_STARTED";
export const GAMES_AWAITING = "GAMES_AWAITING";
export const JOIN_GAME = "JOIN_GAME";
export const GAME_JOINED = "GAME_JOINED";
export const GAME_JOINED_ERROR = "GAME_JOINED_ERROR";
export const ON_MOVE_SELECTED ="ON_MOVE_SELECTED";

