export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const MOVE_SELECTED = "MOVE_SELECTED";
export const HOVER_POSITION ="HOVER_POSITION";
export const PLAYER_PASS ="PLAYER_PASS";
